### ISSUE TITLE
Is it working the same as Matthew's code ? got some few errors there: 

### ISSUE THREAD

**Issue by sssst9s** [J0ker98/stockx-api#3]
Error: StockXAPI is not a constructor
```
const StockXAPI = require('stockx-api');
const stockX = new StockXAPI();

console.log('Logging in...');

stockX.login({
    user: 'accountemailhere', 
    password: 'accountpassword'
})
.then(() => console.log('Logged in successfully!'));
```

**Comment by J0ker98** [comment]
This essentially works the same way. You can try to use the `index.js` provided.

Replace the first two lines with:

`const StockXAPI = require('./src/classes/stockx');
const stockX = new StockXAPI();`

**Comment by sssst9s** [comment]
My bad i didnt catch the fact that in your package u did a index.js with a code sample it works but they block us.

there is a way to bypass this with puppeteer but i guess its useless to rewrite all that code. 
If you have any suggestions/solutions hmu ! thanks @J0ker98 for this modification !
```
Access to this page has been denied because we believe you are using automation tools to browse 
```

**Comment by J0ker98** [comment]
@zaqoQLF Unfortunately this works without doing large amounts of requests to their API. Try using a rotating proxy to see if you manage to bypass that limitation.
